on:
  workflow_run:
    workflows: [autoupdate]
    types:
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
